DROP TABLE IF EXISTS borrower;
DROP TABLE IF EXISTS invoice;

CREATE TABLE borrower (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  borrower_id INTEGER NOT NULL,
  amount REAL(9,2) NOT NULL,
  due_date TIMESTAMP,
  invoice_number TEXT NOT NULL,
  state TEXT NOT NULL DEFAULT "created",
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (borrower_id) REFERENCES borrower (id)
);
